-- Find the list of teams for each stage of the game, which won the duel in a match but still ended up losing the game in UEFA Championship 2022-23.
SELECT
	CASE
		WHEN (SOCCER.TBL_UEFA_2022.TEAM_HOME_SCORE > SOCCER.TBL_UEFA_2022.TEAM_AWAY_SCORE) AND
		(SOCCER.TBL_UEFA_2022.DUELS_WON_AWAY > SOCCER.TBL_UEFA_2022.DUELS_WON_HOME) THEN 		 SOCCER.TBL_UEFA_2022.TEAM_NAME_AWAY
		WHEN (SOCCER.TBL_UEFA_2022.TEAM_HOME_SCORE < SOCCER.TBL_UEFA_2022.TEAM_AWAY_SCORE) AND
		(SOCCER.TBL_UEFA_2022.DUELS_WON_HOME > SOCCER.TBL_UEFA_2022.DUELS_WON_HOME) THEN SOCCER.TBL_UEFA_2022.TEAM_NAME_HOME
		ELSE NULL
	END AS TEAM_LOST,
	SOCCER.TBL_UEFA_2022.STAGE
FROM SOCCER.TBL_UEFA_2022
WHERE TEAM_LOST IS NOT NULL;