-- Find the team with majority possession for maximum number of times during UEFA Champions League 2021-22.
SELECT 
CASE
	WHEN (SOCCER.TBL_UEFA_2021.POSSESSION_HOME > SOCCER.TBL_UEFA_2021.POSSESSION_AWAY) AND (SOCCER.TBL_UEFA_2021.TEAM_NAME_HOME IS NOT NULL) THEN SOCCER.TBL_UEFA_2021.TEAM_NAME_HOME
	WHEN (SOCCER.TBL_UEFA_2021.POSSESSION_HOME < SOCCER.TBL_UEFA_2021.POSSESSION_AWAY) AND
	(SOCCER.TBL_UEFA_2021.TEAM_NAME_AWAY IS NOT NULL) THEN SOCCER.TBL_UEFA_2021.TEAM_NAME_AWAY
END AS TEAM,
COUNT(TEAM) AS MAJORITY_POSSESSION_GAMES
FROM SOCCER.TBL_UEFA_2021
GROUP BY TEAM
ORDER BY COUNT(*) DESC
LIMIT 1